/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pelacak.langganan.digital.ui;

/**
 *
 * @author rifial
 */
@SuppressWarnings("serial")
public class addSubscription extends javax.swing.JDialog {

    public addSubscription() {

        initComponents();
        applyCustomThemeColors();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("REGISTRASI");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        InputUsername = new javax.swing.JTextField();
        buttonadddata = new javax.swing.JButton();
        SubTitle = new javax.swing.JLabel();
        imagepanel = new javax.swing.JPanel();
        buttonaddimage = new javax.swing.JButton();
        InputUsername1 = new javax.swing.JTextField();
        Username1 = new javax.swing.JLabel();
        InputUsername2 = new javax.swing.JTextField();
        Username2 = new javax.swing.JLabel();
        Username3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        Title.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        Title.setText("TAMBAH DATA");

        Username.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        Username.setText("NAMA LAYANAN");

        InputUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsernameActionPerformed(evt);
            }
        });

        buttonadddata.setBackground(new java.awt.Color(0, 51, 204));
        buttonadddata.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        buttonadddata.setForeground(new java.awt.Color(255, 255, 255));
        buttonadddata.setText("SIMPAN DATA");
        buttonadddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonadddataActionPerformed(evt);
            }
        });

        SubTitle.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        SubTitle.setForeground(new java.awt.Color(255, 255, 255));
        SubTitle.setText("SILAHKAN ISI FORM BERIKUT UNTUK MENAMBAHKAN DATA LANGGANAN BARU");

        imagepanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagepanelLayout = new javax.swing.GroupLayout(imagepanel);
        imagepanel.setLayout(imagepanelLayout);
        imagepanelLayout.setHorizontalGroup(
            imagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagepanelLayout.setVerticalGroup(
            imagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        buttonaddimage.setBackground(new java.awt.Color(0, 51, 204));
        buttonaddimage.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        buttonaddimage.setForeground(new java.awt.Color(255, 255, 255));
        buttonaddimage.setText("TAMBAH LOGO");
        buttonaddimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonaddimageActionPerformed(evt);
            }
        });

        InputUsername1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsername1ActionPerformed(evt);
            }
        });

        Username1.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        Username1.setText("BIAYA LAYANAN");

        InputUsername2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsername2ActionPerformed(evt);
            }
        });

        Username2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        Username2.setText("SIKLUS LAYANAN");

        Username3.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        Username3.setText("PEMBAYARAN SELANJUTNYA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonaddimage, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(imagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonadddata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username)
                    .addComponent(InputUsername)
                    .addComponent(InputUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(Username1)
                    .addComponent(InputUsername2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(Username2)
                    .addComponent(Username3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(335, 335, 335))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SubTitle)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubTitle)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Username)
                        .addGap(18, 18, 18)
                        .addComponent(InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Username1)
                        .addGap(18, 18, 18)
                        .addComponent(InputUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Username2)
                        .addGap(18, 18, 18)
                        .addComponent(InputUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Username3)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(buttonadddata, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(imagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonaddimage)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonadddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonadddataActionPerformed

    }//GEN-LAST:event_buttonadddataActionPerformed

    private void InputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsernameActionPerformed

    private void buttonaddimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaddimageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonaddimageActionPerformed

    private void InputUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsername1ActionPerformed

    private void InputUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsername2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputUsername;
    private javax.swing.JTextField InputUsername1;
    private javax.swing.JTextField InputUsername2;
    private javax.swing.JLabel SubTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JLabel Username3;
    private javax.swing.JButton buttonadddata;
    private javax.swing.JButton buttonaddimage;
    private javax.swing.JPanel imagepanel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    // End of variables declaration//GEN-END:variables

    private void applyCustomThemeColors() {
        RegisterTheme.styleDialogBackground(this);
        RegisterTheme.styleLabelColor(Title, RegisterTheme.COLOR_FOREGROUND);
        RegisterTheme.styleLabelColor(SubTitle, RegisterTheme.COLOR_PLACEHOLDER);
        RegisterTheme.styleLabelColor(Username, RegisterTheme.COLOR_FOREGROUND);
        RegisterTheme.styleTextField(InputUsername);
        RegisterTheme.addPlaceholder(InputUsername, "Masukan Username");
        RegisterTheme.styleButton(buttonadddata);
    }

}
