/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pelacak.langganan.digital.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author rifial
 */
@SuppressWarnings("serial")
public class UIFORM extends javax.swing.JFrame {

    /**
     * Creates new form UIFORM
     */
    public UIFORM() {
        initComponents();
        applyCustomTheme();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("  PELACAK LANGGANAN DIGITAL");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabellangganan = new javax.swing.JTable();
        chartfield = new javax.swing.JPanel();
        panelinfo = new javax.swing.JPanel();
        intllabellayanan = new javax.swing.JLabel();
        intllabelbiaya = new javax.swing.JLabel();
        intllabelsiklus = new javax.swing.JLabel();
        intllabeltenggat = new javax.swing.JLabel();
        imagefield = new javax.swing.JPanel();
        subscriptionname = new javax.swing.JLabel();
        billamount = new javax.swing.JLabel();
        subscriptioncycle = new javax.swing.JLabel();
        paymentdeadline = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        loadbutton = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        intllabelbiayatotal = new javax.swing.JLabel();
        labelbiayalangganantotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabellangganan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "LAYANAN", "BIAYA", "SIKLUS", "TENGGAT"
            }
        ));
        jScrollPane1.setViewportView(tabellangganan);

        chartfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout chartfieldLayout = new javax.swing.GroupLayout(chartfield);
        chartfield.setLayout(chartfieldLayout);
        chartfieldLayout.setHorizontalGroup(
            chartfieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartfieldLayout.setVerticalGroup(
            chartfieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        panelinfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        intllabellayanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intllabellayanan.setText("LAYANAN");

        intllabelbiaya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intllabelbiaya.setText("BIAYA");

        intllabelsiklus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intllabelsiklus.setText("SIKLUS");

        intllabeltenggat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intllabeltenggat.setText("TENGGAT");

        imagefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagefield.setPreferredSize(new java.awt.Dimension(160, 160));

        javax.swing.GroupLayout imagefieldLayout = new javax.swing.GroupLayout(imagefield);
        imagefield.setLayout(imagefieldLayout);
        imagefieldLayout.setHorizontalGroup(
            imagefieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        imagefieldLayout.setVerticalGroup(
            imagefieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        subscriptionname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subscriptionname.setText("nama");

        billamount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        billamount.setText("biaya");

        subscriptioncycle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subscriptioncycle.setText("siklus");

        paymentdeadline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymentdeadline.setText("tenggat");

        javax.swing.GroupLayout panelinfoLayout = new javax.swing.GroupLayout(panelinfo);
        panelinfo.setLayout(panelinfoLayout);
        panelinfoLayout.setHorizontalGroup(
            panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoLayout.createSequentialGroup()
                .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(intllabellayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subscriptionname, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelinfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billamount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intllabelbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intllabelsiklus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriptioncycle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(intllabeltenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelinfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(paymentdeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelinfoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(imagefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelinfoLayout.setVerticalGroup(
            panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(intllabellayanan)
                        .addComponent(subscriptionname))
                    .addComponent(imagefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intllabeltenggat)
                    .addComponent(intllabelsiklus)
                    .addComponent(intllabelbiaya))
                .addGap(18, 18, 18)
                .addGroup(panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billamount)
                    .addComponent(subscriptioncycle)
                    .addComponent(paymentdeadline))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        addbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addbutton.setText("TAMBAH");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        editbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editbutton.setText("UBAH");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        deletebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletebutton.setText("HAPUS");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        searchfield.setText("Cari Sesuatu Disini, Hehe...");
        searchfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchfieldFocusLost(evt);
            }
        });

        loadbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadbutton.setText("LOAD");

        savebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        savebutton.setText("SAVE");

        logoutbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutbutton.setText("LOGOUT");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        intllabelbiayatotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        intllabelbiayatotal.setText("TOTAL BIAYA LANGGANAN");

        labelbiayalangganantotal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelbiayalangganantotal.setText("BIAYA LANGGANAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(chartfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 577, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(loadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intllabelbiayatotal)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelbiayalangganantotal, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chartfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intllabelbiayatotal)
                        .addGap(13, 13, 13)
                        .addComponent(labelbiayalangganantotal)
                        .addGap(27, 27, 27))
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        editSubscription es = new editSubscription();
        es.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_editbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

    }//GEN-LAST:event_deletebuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed

        int pilihan = JOptionPane.showConfirmDialog(
                rootPane,
                "Yakin ingin Logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (pilihan == JOptionPane.YES_OPTION) {
            try {
                this.dispose();
                LoginFrame loginFrame = new LoginFrame();
                loginFrame.setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat logout: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void searchfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusGained
        searchfield.setText("");
    }//GEN-LAST:event_searchfieldFocusGained

    private void searchfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusLost
        searchfield.setText("Cari Sesuatu Disini, Hehe...");
    }//GEN-LAST:event_searchfieldFocusLost

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        addSubscription as = new addSubscription();
        as.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_addbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UIFORM().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel billamount;
    private javax.swing.JPanel chartfield;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton editbutton;
    private javax.swing.JPanel imagefield;
    private javax.swing.JLabel intllabelbiaya;
    private javax.swing.JLabel intllabelbiayatotal;
    private javax.swing.JLabel intllabellayanan;
    private javax.swing.JLabel intllabelsiklus;
    private javax.swing.JLabel intllabeltenggat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelbiayalangganantotal;
    private javax.swing.JButton loadbutton;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JPanel panelinfo;
    private javax.swing.JLabel paymentdeadline;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel subscriptioncycle;
    private javax.swing.JLabel subscriptionname;
    private javax.swing.JTable tabellangganan;
    // End of variables declaration//GEN-END:variables

    private void applyCustomTheme() {
        UIFORMTHEME.styleFrameBackground(this);
        UIFORMTHEME.styleButton(addbutton);
        UIFORMTHEME.styleButton(editbutton);
        UIFORMTHEME.styleButton(deletebutton);
        UIFORMTHEME.styleButton(loadbutton);
        UIFORMTHEME.styleButton(logoutbutton);
        UIFORMTHEME.styleButton(savebutton);
        UIFORMTHEME.stylePanelCard(panelinfo);
        UIFORMTHEME.stylePanelCard(chartfield);
        UIFORMTHEME.styleSearchField(searchfield);
        UIFORMTHEME.styleTable(tabellangganan, jScrollPane1);
    }
}
